######################## default configuration ####################

baseURL = "https://example.com"
title = "Yannick Tirand"
theme = "yanka-hugo"

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
disableDefaultLanguageRedirect = false
disableLanguages = []

############################# Plugins ##############################

[module]
[[module.mounts]]
    source = "https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js"
    target = "assets/js/bootstrap.bundle.min.js"

# CSS Plugins
[[params.plugins.css]]
link = "https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css"
[[params.plugins.css]]
link = "https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/hover.css/2.1.0/css/hover-min.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900&display=swap"
[[params.plugins.css]]
link = "plugins/text-animation/text-animation.css"
[[params.plugins.css]]
link = "plugins/hugrid/hugrid.css"

# JS Plugins
[[params.plugins.js]]
link = "https://code.jquery.com/jquery-3.5.1.min.js"
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.js"
[[params.plugins.js]]
link = "plugins/text-animation/text-animation.js"
[[params.plugins.js]]
link = "plugins/hugrid/hugrid.min.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "Home"
URL = "#header"
weight = 1

[[menu.main]]
name = "Portfolio"
URL = "#portfolio"
weight = 2

[[menu.main]]
name = "Experience"
URL = "#experience"
weight = 3

[[menu.main]]
name = "Contact"
URL = "#contact"
weight = 4


#################### default parameters ################################
[params]
copyright = "Copyright Yannick Tirand &copy;"
# Meta data
description = "Software Engineer with broad experience across multiple field - Let’s build something great together!"
author = "Yannick Tirand"
favicon = "images/favicon.png"
google_analytics = "GTM-TVCKBVFM"
logo_light = "images/logo.svg"
logo_dark = "images/logo-dark.svg"

# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.


############################# social site ########################

[[params.social]]
icon = "fab fa-github"
link = "https://github.com/Ynk33"

[[params.social]]
icon = "fab fa-linkedin"
link = "https://www.linkedin.com/in/yannick-tirand-6609213b/"

[[params.social]]
icon = "fas fa-envelope"
link = "mailto:ytirand@gmail.com"

contentDir = "content/english"
weight = 1
home = "Home"
